### ISSUE TITLE
Kilka sugestii/rzeczy do poprawki

### ISSUE THREAD

**Issue by Cich321** [Vilkasek/Raylib---Game#1]
Sprawdzić i ewentualnie poprawić jak są jakieś literówki np. Hiscore.
Możesz trochę przyciemnić tło ew. dodać tryb ciemny żeby było przyjemniejsze dla oka.
Dodanie opcji do gry typu: zmiana rozdziałki, zmiana głośności.
Może jakaś customizacja w opcjach jakieś patterny na tło albo kolory kafelek.
Hitbox "śmietnika" jest za mały i nie wypełnia całego "śmietnika" przez co kafelki lapie się szybciej z lewej strony a jak wylatują to pomimo bycia w teksturze nie są wyłapywane przez grę i przelatują.

**Comment by Vilkasek** [comment]
- [x] Hitboxy
- [x] ~~Opcje~~ Dodałem ekran opcji, ale jeżeli chodzi o zmianę rozdziałki, niestety, ale projektując rozgrywkę nie przewidziałem tego, przez co psuje to całą resztę.
- [x] Przyciemnienie tła / zmienny tint
- [x] Literówki

**Comment by Vilkasek** [comment]
Jak na razie wszystkie sugestie, które byłem w stanie dodać dodałem
